//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Bussines_Object_Layer_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestEntities2 : DbContext
    {
        public TestEntities2()
            : base("name=TestEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Address> tb_Address { get; set; }
        public virtual DbSet<tb_Area> tb_Area { get; set; }
        public virtual DbSet<tb_City> tb_City { get; set; }
        public virtual DbSet<tb_Class> tb_Class { get; set; }
        public virtual DbSet<tb_Paper> tb_Paper { get; set; }
        public virtual DbSet<tb_Role> tb_Role { get; set; }
        public virtual DbSet<tb_Staff> tb_Staff { get; set; }
        public virtual DbSet<tb_State> tb_State { get; set; }
        public virtual DbSet<tb_Student> tb_Student { get; set; }
        public virtual DbSet<tb_Subject> tb_Subject { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
    }
}
