//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Bussines_Object_Layer_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Paper
    {
        public int Paper_Id { get; set; }
        public string Paper_Name { get; set; }
        public Nullable<decimal> Paper_Sub_Marks { get; set; }
        public Nullable<decimal> Paper_Obt_Marks { get; set; }
        public int Std_Id { get; set; }
        public int Sub_Id { get; set; }
        public int Class_Id { get; set; }
    
        public virtual tb_Class tb_Class { get; set; }
        public virtual tb_Student tb_Student { get; set; }
        public virtual tb_Subject tb_Subject { get; set; }
    }
}
