//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Bussines_Object_Layer_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Staff()
        {
            this.tb_Subject = new HashSet<tb_Subject>();
        }
    
        public int Stf_Id { get; set; }
        public string Stf_Name { get; set; }
        public string Stf_Gender { get; set; }
        public Nullable<decimal> Stf_Salary { get; set; }
        public Nullable<System.DateTime> Stf_Created_On_Date { get; set; }
        public int Stf_Created_Buy { get; set; }
        public int Address_Id { get; set; }
        public int Isselect { get; set; }
        public virtual tb_Address tb_Address { get; set; }
        public virtual tb_User tb_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Subject> tb_Subject { get; set; }
    }
}
