//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Bussines_Object_Layer_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Subject()
        {
            this.tb_Paper = new HashSet<tb_Paper>();
        }
    
        public int Sub_Id { get; set; }
        public string Sub_Name { get; set; }
        public int Stf_Id { get; set; }
        public int Class_Id { get; set; }
        public int Isselect { get; set; }

        public virtual tb_Class tb_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Paper> tb_Paper { get; set; }
        public virtual tb_Staff tb_Staff { get; set; }
    }
}
